### ISSUE TITLE
"Preset package is missing a renovate-config entry" using Github Package Registry

### ISSUE THREAD

**Issue by rebeccatang16** [whitesource/renovate-on-prem#130] opened 2021-01-09 03:52 UTC
Hi!

We are switching from npmjs to Github Package Registry for npm packages, and are now encountering this error from renovate (version 1.2.0):
`Preset package is missing a renovate-config entry (@orgName)`

I updated the `.npmrc` in the bot's homedir to:
```
//registry.npmjs.org/:_authToken=XXXX
//npm.pkg.github.com/:_authToken=XXXX
@orgName:registry=https://npm.pkg.github.com
```
(I've also tried it with the npmjs token line removed)

The github token has read:packages, and the account it's associated with has access to all the necessary repos, including renovate-config. Our `@orgName/renovate-config` repo has a "renovate-config" section in its package.json, plus it worked before the registry change.

The repos we're getting failures on extend the preset configs the standard way, with
```
{
  "extends": [
    "@orgName"
  ],
...
```

Any advice on what's wrong? Or is it possible that renovate doesn't play nicely with Github Packages Registry?

**Comment by rarkins** [comment] 2021-01-09 07:27
> Any advice on what's wrong? Or is it possible that renovate doesn't play nicely with Github Packages Registry?

I haven't tested this scenario, so it's possible that this is the cause. Can you reproduce the same problem when using the regular CLI? In that case we rule out that the problem is specific to WhiteSource Renovate On-Prem and can debug it in the main repo.

**Comment by rarkins** [comment] 2021-01-09 07:28
BTW my recommendation would be to use regular GitHub repos for presets instead of packages though - much simpler and less things to go wrong.

**Comment by wyardley** [comment] 2021-01-09 18:17
Yes, the command line works Ok; from execing into the container (just using the `.npmrc` we dropped in:
```
ubuntu@renovate-pro-webhook-8444ccfc65-pwq6l:/usr/src/app$ /usr/local/node/14.15.3/bin/npm info @ogName/renovate-config
@orgName/renovate-config@1.8.6 | UNLICENSED | deps: none | versions: 41
[...]
published 4 days ago by undefined <undefined>
```

> BTW my recommendation would be to use regular GitHub repos for presets instead of packages though - much simpler and less things to go wrong.

Unfortunately, there are many hundreds of repos with the existing config, so it wouldn't be a quick effort to switch over, though we did notice that that's an option.

We also took a look through some of the stuff in https://github.com/renovatebot/renovate/issues/5646 (which isn't exactly the same issue), and also tested different scenarios including adding the trailing newline to the `.npmrc`.

**Comment by rarkins** [comment] 2021-01-11 08:33
I meant command line `renovate`. I'm hoping to narrow down if this is specific to this distribution or a common problem with all Renovate

**Comment by Charles546** [comment] 2021-01-11 19:18
From the renovate source here https://github.com/renovatebot/renovate/blob/44a33bcd4bda3dda0d52f74ff9a1eaea6fd766de/lib/datasource/npm/get.ts#L69-L163, it looks like that it queries the registry for the metadata of the package for the preset, and load the `renovate-config` there.

We just found out that, when getting the metadata, the github packages metadata doesn't include the `renovate-config` block.

If you run the following command, you will see that the `renovate-config` is missing from the output of the versions.

```
curl -s -H 'Authorization: bearer <redactted>' https://npm.pkg.github.com/@<org>/renovate-config |jq .
```

For comparison, if you query npmjs.org, you will see the `renovate-config` blocks in the output.

```
curl -s -H 'Authorization: bearer <redactted>' https://registry.npmjs.org/@<org>/renovate-config |jq .
```

**Comment by rebeccatang16** [comment] 2021-01-11 19:47
Tried out cli `renovate`, following https://github.com/renovatebot/renovate/blob/master/docs/usage/self-hosting.md

My renovate-config.js was:
```
module.exports = {
    token: 'XXXXX',
    platform: 'github',
    logLevel: 'debug',
    onboardingConfig: {
        extends: ['@orgName'],
    },
    repositories: ['orgName/test-repo'],
};
```

Got the same error:
```
 INFO: Throwing preset error (repository=orgName/test-repo)
       "validationError": "Preset package is missing a renovate-config entry (@orgName:automergeDev)"
 INFO: Repository has invalid config (repository=orgName/test-repo)
       "error": {
         "validationError": "Preset package is missing a renovate-config entry (@orgName:automergeDev)",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/Users/rktang/.nvm/versions/node/v12.18.1/lib/node_modules/renovate/dist/config/presets/index.js:234:35)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
```

**Comment by wyardley** [comment] 2021-01-11 20:54
Can we use the `force` object to override the config in `renovate.json` to `github>orgname/renovate-config`? And if so, and we do this, it would still pick up overrides, right?

We do have some smaller number of projects that are using a specific named prefix, so we'd have to sort out how that would work, but this might help as a short-term fix, at least.

**Comment by rarkins** [comment] 2021-01-12 08:22
@wyardley are you using the same scope on npm as well as ghcr? e.g. need to use the same `@orgName` on both? Otherwise I'd suggest publishing a new version of your `@orgName` preset that simply extends the GitHub url.

Assuming you can't point npm to `npmjs` just for your preset package, you *could* try using `force` to change the `extends` array. The problem with this is that if any repos have something *other* than `extends: ["@orgname"]` then they will lose that difference once you force it to be `"extends": ["github>orgname/renovate-config"]`.

> And if so, and we do this, it would still pick up overrides, right?

I'm not sure what you mean by overrides, but the `force` object will completely replace anything the repo has.

Because this is not WhiteSource On-Prem specific, I would like to close this issue and discuss in https://github.com/renovatebot/renovate/discussions instead where there's a wider audience plus better chance of someone finding the discussion in future if they have the same problem.

> I assume a workaround checking if the target is the GitHub registry and then pulling the package and grabbing the metadata from there instead would probably not be ideal? We've opened a GHE support request to get a bit more context about whether this data being missing from the package metadata is intentional or not...

Let's discuss it in the main repo, as that's where the code would need to be written

**Closed by rarkins** 2021-01-12 08:22 UTC

**Comment by rebeccatang16** [comment] 2021-01-12 18:22
Opened this discussion https://github.com/renovatebot/renovate/discussions/8266
