### ISSUE TITLE
Handle `check_suite` and `check_run` webhooks

### ISSUE THREAD

**Issue by jftanner** [whitesource/renovate-on-prem#160] opened 2021-08-18 12:53 UTC
I'm using Renovate-on-Prem with a Github Enterprise 2.22 installation, and it's working great in most ways, but I'm having an issue with webhooks for auto-merging PRs.

Most of my repos have a check suite (ironically, a WhiteSource Security Check) that runs for all PRs which change dependencies. Because the [github configuration documentation](https://github.com/whitesource/renovate-on-prem/blob/main/docs/configuration-github.md#provision-app) says to enable events for check runs, I would have expected the bot to re-check PRs after the runs complete and therefore trigger a new job once its auto-mergable PRs are ready. However, the bot appears to ignore these events and won't merge the PR until its next scheduled run.

Here are the debug logs from the bot (with the repo and installation ID redacted for security reasons):
```
DEBUG: LOG_CONTEXT: undefined
DEBUG: Received webhook event (repository=myorg/myrepo)
       "event": "check_suite",
       "action": "completed",
       "installationId": 1234
DEBUG: Ignoring event type: check_suite (repository=myorg/myrepo)
DEBUG: LOG_CONTEXT: undefined
DEBUG: Received webhook event (repository=myorg/myrepo)
       "event": "check_run",
       "action": "completed",
       "installationId": 1234
DEBUG: Ignoring event type: check_run (repository=myorg/myrepo)
```

Maybe I'm missing something, and this is a misconfiguration on my part. If so, I'd love a pointer in the right direction. If not, I think the webhook handler just needs to treat the `check_suite:completed` and `check_run:completed` events like it would status checks.

(On a side note, it also appears to ignore `security_advisory` events as well, though I'm not sure how it should be handling those in general.)

**Comment by jftanner** [comment] 2021-08-18 12:54
I've got the following event settings in the Github App:
![image](https://user-images.githubusercontent.com/10095474/129901490-624310e4-ff62-4d2c-b5b6-784c3de3e8ce.png)

**Comment by rarkins** [comment] 2021-08-18 14:46
> Maybe I'm missing something, and this is a misconfiguration on my part. If so, I'd love a pointer in the right direction. If not, I think the webhook handler just needs to treat the `check_suite:completed` and `check_run:completed` events like it would status checks.

Renovate doesn't actually react to any status checks or check runs. The problem is that a repo might have even 10s of checks and if we were to run a job every time we get a passing test then it would quickly use up GitHub API limits plus consume a lot of Renovate cycles too.
 
I think a better solution would be for Renovate to enable GitHub's native automerge so that it can do the merge after all tests pass without Renovate needing to run?

> (On a side note, it also appears to ignore `security_advisory` events as well, though I'm not sure how it should be handling those in general.)

That one might be reasonable to run after, but in general we favor running a dynamic job for scenarios where the user might be *waiting* for it (e.g. they merged one PR which made a second PR get conflicted).

**Comment by jftanner** [comment] 2021-08-18 15:11
Thanks for the quick response!

At the moment, is it normal behavior to wait until the next scheduled run, rather than auto-merging immediately once the PR is ready? (Perhaps that's the thing I was confused about; I may have been assuming it was intended to do something that it's not.)

If that's the case, should those extraneous events be removed from the documentation? Or is there an intent to use them later for more features?

What about PR review events? I've _also_ got a separate bot that approves auto-mergable PRs from Renovate (I couldn't use the standard one for technical reasons, but it was easy enough to write.) If Renovate-on-Prem handles PR review approvals, maybe I could just have my bot hold off on approving until after status checks all pass?

> a better solution would be for Renovate to enable GitHub's native automerge

I'm not sure if that's available in the version of GHE we're using, but it sounds like a good solution.

**Comment by rarkins** [comment] 2021-08-18 15:57
> At the moment, is it normal behavior to wait until the next scheduled run, rather than auto-merging immediately once the PR is ready? (Perhaps that's the thing I was confused about; I may have been assuming it was intended to do something that it's not.)

That is expected, yes - for reasons I tried explaining above. It would be highly inefficient to run every time a test passed, or even to do the query necessary of the GitHub API to decide if the branch was ready for automerge.
 
> If that's the case, should those extraneous events be removed from the documentation? Or is there an intent to use them later for more features?

There was an intent to use them, for example if GitHub created a "unified" API to query both status checks and check runs combined status together.

> What about PR review events? I've _also_ got a separate bot that approves auto-mergable PRs from Renovate (I couldn't use the standard one for technical reasons, but it was easy enough to write.) If Renovate-on-Prem handles PR review approvals, maybe I could just have my bot hold off on approving until after status checks all pass?

Such events aren't used, for similar reasons.

> > a better solution would be for Renovate to enable GitHub's native automerge
> 
> I'm not sure if that's available in the version of GHE we're using, but it sounds like a good solution.

I'm sure it will be arriving soon, and that's going to be our only solution for this.

Will close this now, as we don't plan to queue jobs for every branch which has a test pass as it would be too inefficient.

**Closed by rarkins** 2021-08-18 15:57 UTC

**Comment by jftanner** [comment] 2021-08-18 16:31
Awesome, thank you @rarkins. I appreciate your insight here.

In this case, I'll give a +1 to https://github.com/whitesource/renovate-on-prem/issues/49, as it'd be useful to be able to trigger a new scan from an external process once it determines that the checks have passed and the pr is ready to go.

Auto-merge-when-ready would be even better.
